// <auto-generated />
using System;
using EduPrime.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPrime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231001014201_AddNullableToUpdatedOnProfessor")]
    partial class AddNullableToUpdatedOnProfessor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AreaEmployee", b =>
                {
                    b.Property<int>("AreasId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.HasKey("AreasId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("AreaEmployee");

                    b.HasData(
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 1
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 2
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 4
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 5
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 6
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 3
                        },
                        new
                        {
                            AreasId = 2,
                            EmployeesId = 2
                        },
                        new
                        {
                            AreasId = 2,
                            EmployeesId = 3
                        },
                        new
                        {
                            AreasId = 3,
                            EmployeesId = 7
                        },
                        new
                        {
                            AreasId = 3,
                            EmployeesId = 8
                        },
                        new
                        {
                            AreasId = 4,
                            EmployeesId = 9
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 932, DateTimeKind.Local).AddTicks(3151));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9693),
                            Description = "Only those who teach a subject",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9696),
                            Description = "Office administrative area",
                            Name = "Office administrative"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9697),
                            Description = "School clean service",
                            Name = "Clean service"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9699),
                            Description = "School security guard",
                            Name = "Security guard"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 932, DateTimeKind.Local).AddTicks(6707));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RfcDocument")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1988, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9898),
                            Email = "BrendaLopez@school.com",
                            Name = "Brenda",
                            PhoneNumber = "8445678787",
                            Surname = "Lopez Reyes"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9902),
                            Email = "AlmaRosa@school.com",
                            Name = "Alma Rosa",
                            PhoneNumber = "8445567556",
                            Surname = "Aguilar Tejada"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9904),
                            Email = "LorenaSuarez@school.com",
                            Name = "Lorena",
                            PhoneNumber = "8445552552",
                            Surname = "Suarez Treviño"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1985, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9906),
                            Email = "RamiroTorrero@school.com",
                            Name = "Ramiro",
                            PhoneNumber = "8449883834",
                            Surname = "Torrero Salinas"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1990, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9908),
                            Email = "MarisolTorres@school.com",
                            Name = "Marisol",
                            PhoneNumber = "8445556781",
                            Surname = "Torres Valdés"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1980, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9910),
                            Email = "SofiaCardenas@school.com",
                            Name = "Sofía",
                            PhoneNumber = "8445556781",
                            Surname = "Cárdenas Berrendo"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1981, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9912),
                            Email = "ReginaGonzales@school.com",
                            Name = "Regina",
                            PhoneNumber = "8446787575",
                            Surname = "Gonzales Perreira"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1975, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9914),
                            Email = "VeronicaZertuche@school.com",
                            Name = "Verónica",
                            PhoneNumber = "8449990023",
                            Surname = "Zertuche Mora"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1975, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9916),
                            Email = "LuisCarranza@school.com",
                            Name = "Luis",
                            PhoneNumber = "8445678787",
                            Surname = "Carranza Allende"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 933, DateTimeKind.Local).AddTicks(3419));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Satisfaction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOnDuty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(91),
                            EmployeeId = 1,
                            Satisfaction = 85,
                            YearsOnDuty = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(93),
                            EmployeeId = 2,
                            Satisfaction = 90,
                            YearsOnDuty = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(95),
                            EmployeeId = 3,
                            Satisfaction = 90,
                            YearsOnDuty = 15
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(99),
                            EmployeeId = 4,
                            Satisfaction = 100,
                            YearsOnDuty = 10
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(101),
                            EmployeeId = 5,
                            Satisfaction = 45,
                            YearsOnDuty = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(102),
                            EmployeeId = 6,
                            Satisfaction = 100,
                            YearsOnDuty = 10
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ProfessorsSubjects");

                    b.HasData(
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 7
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            ProfessorId = 4,
                            SubjectId = 6
                        },
                        new
                        {
                            ProfessorId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            ProfessorId = 5,
                            SubjectId = 10
                        },
                        new
                        {
                            ProfessorId = 6,
                            SubjectId = 9
                        },
                        new
                        {
                            ProfessorId = 6,
                            SubjectId = 12
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 934, DateTimeKind.Local).AddTicks(3596));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(419),
                            Name = "PrimaryRole"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(420),
                            Name = "AdminRole"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(421),
                            Name = "StandardRole"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 934, DateTimeKind.Local).AddTicks(6865));

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(213),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Emiliano",
                            PhoneNumber = "8445556767",
                            Surname = "Romero Salínas"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(215),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Omar",
                            PhoneNumber = "8445556767",
                            Surname = "Martínez Reyes"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(217),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Verónica",
                            PhoneNumber = "8446789900",
                            Surname = "Sánchez"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1999, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(220),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Jimena",
                            PhoneNumber = "8442225656",
                            Surname = "Trejo González"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(222),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Daniel",
                            PhoneNumber = "8442225656",
                            Surname = "Aranda Martín"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1999, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(224),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Valeria",
                            PhoneNumber = "8445556776",
                            Surname = "Guzmán Allende"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1998, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(226),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Julian",
                            PhoneNumber = "8445676767",
                            Surname = "Torres Cabrera"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1998, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(228),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Juan",
                            PhoneNumber = "8445676767",
                            Surname = "Aguilar Cabello"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1998, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(230),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Gabriela",
                            PhoneNumber = "8445676767",
                            Surname = "Agustín Neida"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(231),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Pedro",
                            PhoneNumber = "8445676767",
                            Surname = "Ignácio Carranza"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1997, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(234),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Amanda",
                            PhoneNumber = "8445582019",
                            Surname = "Treviño Almeda"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1997, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(236),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Jessica",
                            PhoneNumber = "8445582019",
                            Surname = "Ramos Irigoyen"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FirstGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SecondGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentsSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(314),
                            FinalGrade = 0,
                            FirstGrade = 91,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(318),
                            FinalGrade = 0,
                            FirstGrade = 71,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(320),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(321),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(323),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(325),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(327),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(328),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(330),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(332),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(334),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(335),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(338),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(339),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(341),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(343),
                            FinalGrade = 0,
                            FirstGrade = 85,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(345),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(347),
                            FinalGrade = 0,
                            FirstGrade = 95,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(349),
                            FinalGrade = 0,
                            FirstGrade = 85,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(350),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(352),
                            FinalGrade = 0,
                            FirstGrade = 95,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(354),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(355),
                            FinalGrade = 0,
                            FirstGrade = 87,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(357),
                            FinalGrade = 0,
                            FirstGrade = 65,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(359),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(361),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(362),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(364),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(366),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(368),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(369),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(371),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(373),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(375),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(377),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(378),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSemester")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(6163));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(140),
                            Name = "Matemáticas I"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(145),
                            Name = "Matemáticas II"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(149),
                            Name = "Matemáticas III"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(142),
                            Name = "Física I"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(146),
                            Name = "Física II"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(150),
                            Name = "Física III"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(144),
                            Name = "Historia"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(148),
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = 9,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(151),
                            Name = "Química I"
                        },
                        new
                        {
                            Id = 10,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(152),
                            Name = "Filosofía"
                        },
                        new
                        {
                            Id = 11,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(153),
                            Name = "Informática"
                        },
                        new
                        {
                            Id = 12,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2023, 9, 30, 19, 42, 0, 936, DateTimeKind.Local).AddTicks(155),
                            Name = "Química II"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 9, 30, 19, 42, 0, 935, DateTimeKind.Local).AddTicks(9136));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AreaEmployee", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Employee", "Employee")
                        .WithOne("Professor")
                        .HasForeignKey("EduPrime.Core.Entities.Professor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Professor", "Professor")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Student", "Student")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Navigation("StudentsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Navigation("ProfessorsSubjects");

                    b.Navigation("StudentsSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
