// <auto-generated />
using System;
using EduPrime.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPrime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240616023843_IgnoreCreatedOnAndUpdatedOnFieldsForPermissionsRoles")]
    partial class IgnoreCreatedOnAndUpdatedOnFieldsForPermissionsRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AreaEmployee", b =>
                {
                    b.Property<int>("AreasId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeesId")
                        .HasColumnType("int");

                    b.HasKey("AreasId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("AreaEmployee");

                    b.HasData(
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 1
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 2
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 4
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 5
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 6
                        },
                        new
                        {
                            AreasId = 1,
                            EmployeesId = 3
                        },
                        new
                        {
                            AreasId = 2,
                            EmployeesId = 2
                        },
                        new
                        {
                            AreasId = 2,
                            EmployeesId = 3
                        },
                        new
                        {
                            AreasId = 3,
                            EmployeesId = 7
                        },
                        new
                        {
                            AreasId = 3,
                            EmployeesId = 8
                        },
                        new
                        {
                            AreasId = 4,
                            EmployeesId = 9
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 946, DateTimeKind.Utc).AddTicks(4040));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8710),
                            Description = "Only those who teach a subject",
                            Name = "Professor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8710),
                            Description = "Office administrative area",
                            Name = "Office administrative"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8710),
                            Description = "School clean service",
                            Name = "Clean service"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8710),
                            Description = "School security guard",
                            Name = "Security guard"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 946, DateTimeKind.Utc).AddTicks(5170));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RfcDocument")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1988, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8810),
                            Email = "BrendaLopez@school.com",
                            Name = "Brenda",
                            PhoneNumber = "8445678787",
                            Surname = "Lopez Reyes"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8820),
                            Email = "AlmaRosa@school.com",
                            Name = "Alma Rosa",
                            PhoneNumber = "8445567556",
                            Surname = "Aguilar Tejada"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8820),
                            Email = "LorenaSuarez@school.com",
                            Name = "Lorena",
                            PhoneNumber = "8445552552",
                            Surname = "Suarez Treviño"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1985, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8830),
                            Email = "RamiroTorrero@school.com",
                            Name = "Ramiro",
                            PhoneNumber = "8449883834",
                            Surname = "Torrero Salinas"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1990, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8830),
                            Email = "MarisolTorres@school.com",
                            Name = "Marisol",
                            PhoneNumber = "8445556781",
                            Surname = "Torres Valdés"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1980, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8830),
                            Email = "SofiaCardenas@school.com",
                            Name = "Sofía",
                            PhoneNumber = "8445556781",
                            Surname = "Cárdenas Berrendo"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1981, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8830),
                            Email = "ReginaGonzales@school.com",
                            Name = "Regina",
                            PhoneNumber = "8446787575",
                            Surname = "Gonzales Perreira"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1975, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8830),
                            Email = "VeronicaZertuche@school.com",
                            Name = "Verónica",
                            PhoneNumber = "8449990023",
                            Surname = "Zertuche Mora"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1975, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8840),
                            Email = "LuisCarranza@school.com",
                            Name = "Luis",
                            PhoneNumber = "8445678787",
                            Surname = "Carranza Allende"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 946, DateTimeKind.Utc).AddTicks(6600));

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.PermissionRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("PermissionsRoles");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 946, DateTimeKind.Utc).AddTicks(9940));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Satisfaction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOnDuty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 1,
                            Satisfaction = 85,
                            YearsOnDuty = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 2,
                            Satisfaction = 90,
                            YearsOnDuty = 30
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 3,
                            Satisfaction = 90,
                            YearsOnDuty = 15
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 4,
                            Satisfaction = 100,
                            YearsOnDuty = 10
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 5,
                            Satisfaction = 45,
                            YearsOnDuty = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8920),
                            EmployeeId = 6,
                            Satisfaction = 100,
                            YearsOnDuty = 10
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ProfessorsSubjects");

                    b.HasData(
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 4
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 7
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 2
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 5
                        },
                        new
                        {
                            ProfessorId = 4,
                            SubjectId = 6
                        },
                        new
                        {
                            ProfessorId = 5,
                            SubjectId = 3
                        },
                        new
                        {
                            ProfessorId = 5,
                            SubjectId = 10
                        },
                        new
                        {
                            ProfessorId = 6,
                            SubjectId = 9
                        },
                        new
                        {
                            ProfessorId = 6,
                            SubjectId = 12
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(2850));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9110),
                            Name = "Primary"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9110),
                            Name = "Admim"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9110),
                            Name = "Standard"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9110),
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(3750));

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8990),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Emiliano",
                            PhoneNumber = "8445556767",
                            Surname = "Romero Salínas"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8990),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Omar",
                            PhoneNumber = "8445556767",
                            Surname = "Martínez Reyes"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9000),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            Name = "Verónica",
                            PhoneNumber = "8446789900",
                            Surname = "Sánchez"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1999, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9010),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Jimena",
                            PhoneNumber = "8442225656",
                            Surname = "Trejo González"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1999, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9010),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Daniel",
                            PhoneNumber = "8442225656",
                            Surname = "Aranda Martín"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1999, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            Name = "Valeria",
                            PhoneNumber = "8445556776",
                            Surname = "Guzmán Allende"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1998, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Julian",
                            PhoneNumber = "8445676767",
                            Surname = "Torres Cabrera"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1998, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Juan",
                            PhoneNumber = "8445676767",
                            Surname = "Aguilar Cabello"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1998, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            Name = "Gabriela",
                            PhoneNumber = "8445676767",
                            Surname = "Agustín Neida"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1997, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Pedro",
                            PhoneNumber = "8445676767",
                            Surname = "Ignácio Carranza"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1997, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9020),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Amanda",
                            PhoneNumber = "8445582019",
                            Surname = "Treviño Almeda"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1997, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9030),
                            CurrentSemester = 4,
                            EmergencyContact = "8445677676",
                            Name = "Jessica",
                            PhoneNumber = "8445582019",
                            Surname = "Ramos Irigoyen"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(6020));

                    b.Property<int>("FinalGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FirstGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SecondGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentsSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9040),
                            FinalGrade = 0,
                            FirstGrade = 91,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9040),
                            FinalGrade = 0,
                            FirstGrade = 71,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9040),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 1,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9050),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 85,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 6,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 95,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9060),
                            FinalGrade = 0,
                            FirstGrade = 85,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9070),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 7,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9070),
                            FinalGrade = 0,
                            FirstGrade = 95,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9070),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9070),
                            FinalGrade = 0,
                            FirstGrade = 87,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 8,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9070),
                            FinalGrade = 0,
                            FirstGrade = 65,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 7,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 8,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 9,
                            SubjectId = 9,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 10,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9080),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9090),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 11,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9090),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 10,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9090),
                            FinalGrade = 0,
                            FirstGrade = 50,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 11,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9090),
                            FinalGrade = 0,
                            FirstGrade = 70,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 12,
                            SubjectId = 12,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(9090),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSemester")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(6990));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8940),
                            Name = "Matemáticas I"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8940),
                            Name = "Matemáticas II"
                        },
                        new
                        {
                            Id = 7,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Matemáticas III"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8940),
                            Name = "Física I"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8940),
                            Name = "Física II"
                        },
                        new
                        {
                            Id = 8,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Física III"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8940),
                            Name = "Historia"
                        },
                        new
                        {
                            Id = 6,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Finanzas"
                        },
                        new
                        {
                            Id = 9,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Química I"
                        },
                        new
                        {
                            Id = 10,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Filosofía"
                        },
                        new
                        {
                            Id = 11,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8950),
                            Name = "Informática"
                        },
                        new
                        {
                            Id = 12,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8960),
                            Name = "Química II"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 6, 16, 2, 38, 42, 947, DateTimeKind.Utc).AddTicks(8460));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationToken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime?>("VerificationTokenExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AreaEmployee", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPrime.Core.Entities.PermissionRole", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Permission", "Permission")
                        .WithMany("PermissionsRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Role", "Role")
                        .WithMany("PermissionsRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Employee", "Employee")
                        .WithOne("Professor")
                        .HasForeignKey("EduPrime.Core.Entities.Professor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Professor", "Professor")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Student", "Student")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Permission", b =>
                {
                    b.Navigation("PermissionsRoles");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Role", b =>
                {
                    b.Navigation("PermissionsRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Navigation("StudentsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Navigation("ProfessorsSubjects");

                    b.Navigation("StudentsSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
