// <auto-generated />
using System;
using EduPrime.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduPrime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduPrime.Core.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 18, 22, 51, 54, 622, DateTimeKind.Local).AddTicks(1416));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("isDeleted = 'false'");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6003),
                            Description = "Only those who teach a subject",
                            IsDeleted = false,
                            Name = "Professor"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6006),
                            Description = "Office administrative area",
                            IsDeleted = false,
                            Name = "Office administrative"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6007),
                            Description = "School clean service",
                            IsDeleted = false,
                            Name = "Clean service"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6008),
                            Description = "School security guard",
                            IsDeleted = false,
                            Name = "Security guard"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.AreaEmployee", b =>
                {
                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AreaId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AreasEmployees");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            EmployeeId = 1
                        },
                        new
                        {
                            AreaId = 1,
                            EmployeeId = 2
                        },
                        new
                        {
                            AreaId = 2,
                            EmployeeId = 2
                        },
                        new
                        {
                            AreaId = 2,
                            EmployeeId = 3
                        },
                        new
                        {
                            AreaId = 1,
                            EmployeeId = 3
                        },
                        new
                        {
                            AreaId = 3,
                            EmployeeId = 4
                        },
                        new
                        {
                            AreaId = 4,
                            EmployeeId = 5
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Picture")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RfcDocument")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1988, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6435),
                            Email = "BrendaLopez@school.com",
                            IsDeleted = false,
                            Name = "Brenda",
                            PhoneNumber = "8445678787",
                            Surname = "Lopez Reyes"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6439),
                            Email = "AlmaRosa@school.com",
                            IsDeleted = false,
                            Name = "Alma Rosa",
                            PhoneNumber = "8445567556",
                            Surname = "Aguilar Tejada"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6442),
                            Email = "LorenaSuarez@school.com",
                            IsDeleted = false,
                            Name = "Lorena",
                            PhoneNumber = "8445552552",
                            Surname = "Suarez Treviño"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1981, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6444),
                            Email = "ReginaGonzales@school.com",
                            IsDeleted = false,
                            Name = "Regina",
                            PhoneNumber = "8446787575",
                            Surname = "Gonzales Perreira"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1975, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6446),
                            Email = "LuisCarranza@school.com",
                            IsDeleted = false,
                            Name = "Luis",
                            PhoneNumber = "8445678787",
                            Surname = "Carranza Allende"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Satisfaction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("YearsOnDuty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Professors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            IsDeleted = false,
                            Satisfaction = 85,
                            YearsOnDuty = 5
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            IsDeleted = false,
                            Satisfaction = 90,
                            YearsOnDuty = 30
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            IsDeleted = false,
                            Satisfaction = 90,
                            YearsOnDuty = 15
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ProfessorsSubjects");

                    b.HasData(
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 2,
                            SubjectId = 2
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            ProfessorId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 4
                        },
                        new
                        {
                            ProfessorId = 1,
                            SubjectId = 5
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 18, 22, 51, 54, 624, DateTimeKind.Local).AddTicks(242));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6682),
                            IsDeleted = false,
                            Name = "PrimaryRole"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6683),
                            IsDeleted = false,
                            Name = "AdminRole"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6684),
                            IsDeleted = false,
                            Name = "StandardRole"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Picture")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6609),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Emiliano",
                            PhoneNumber = "8445556767",
                            Surname = "Salinas"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6612),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Omar",
                            PhoneNumber = "8445556767",
                            Surname = "Reyes"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6614),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Jimena",
                            PhoneNumber = "8442225656",
                            Surname = "Trejo"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6616),
                            CurrentSemester = 2,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Daniel",
                            PhoneNumber = "8442225656",
                            Surname = "Aranda"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2000, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6618),
                            CurrentSemester = 3,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Julian",
                            PhoneNumber = "8445676767",
                            Surname = "Torres"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6620),
                            CurrentSemester = 1,
                            EmergencyContact = "8445677676",
                            IsDeleted = false,
                            Name = "Verónica",
                            PhoneNumber = "8446789900",
                            Surname = "Sánchez"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("FirstGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SecondGrade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("StudentsSubjects");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6649),
                            FinalGrade = 91,
                            FirstGrade = 91,
                            SecondGrade = 92,
                            Status = 1
                        },
                        new
                        {
                            StudentId = 2,
                            SubjectId = 1,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6651),
                            FinalGrade = 58,
                            FirstGrade = 71,
                            SecondGrade = 45,
                            Status = 2
                        },
                        new
                        {
                            StudentId = 3,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6653),
                            FinalGrade = 0,
                            FirstGrade = 90,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 4,
                            SubjectId = 2,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6655),
                            FinalGrade = 0,
                            FirstGrade = 100,
                            SecondGrade = 0,
                            Status = 0
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 3,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6657),
                            FinalGrade = 90,
                            FirstGrade = 90,
                            SecondGrade = 90,
                            Status = 1
                        },
                        new
                        {
                            StudentId = 5,
                            SubjectId = 4,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6659),
                            FinalGrade = 45,
                            FirstGrade = 50,
                            SecondGrade = 40,
                            Status = 2
                        },
                        new
                        {
                            StudentId = 6,
                            SubjectId = 5,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6660),
                            FinalGrade = 0,
                            FirstGrade = 80,
                            SecondGrade = 80,
                            Status = 0
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSemester")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSemester = 1,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6551),
                            IsDeleted = false,
                            Name = "Matemáticas I"
                        },
                        new
                        {
                            Id = 2,
                            AvailableSemester = 2,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6553),
                            IsDeleted = false,
                            Name = "Matemáticas II"
                        },
                        new
                        {
                            Id = 3,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6554),
                            IsDeleted = false,
                            Name = "Matemáticas III"
                        },
                        new
                        {
                            Id = 4,
                            AvailableSemester = 3,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6555),
                            IsDeleted = false,
                            Name = "Física I"
                        },
                        new
                        {
                            Id = 5,
                            AvailableSemester = 4,
                            CreatedOn = new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(6557),
                            IsDeleted = false,
                            Name = "Física II"
                        });
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 7, 18, 22, 51, 54, 625, DateTimeKind.Local).AddTicks(5660));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.AreaEmployee", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Area", "Area")
                        .WithMany("AreasEmployees")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Employee", "Employee")
                        .WithMany("AreasEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Employee", null)
                        .WithOne("Professor")
                        .HasForeignKey("EduPrime.Core.Entities.Professor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EduPrime.Core.Entities.ProfessorSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Professor", "Professor")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("ProfessorsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.StudentSubject", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Student", "Student")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduPrime.Core.Entities.Subject", "Subject")
                        .WithMany("StudentsSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.User", b =>
                {
                    b.HasOne("EduPrime.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Area", b =>
                {
                    b.Navigation("AreasEmployees");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Employee", b =>
                {
                    b.Navigation("AreasEmployees");

                    b.Navigation("Professor")
                        .IsRequired();
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Student", b =>
                {
                    b.Navigation("StudentsSubjects");
                });

            modelBuilder.Entity("EduPrime.Core.Entities.Subject", b =>
                {
                    b.Navigation("ProfessorsSubjects");

                    b.Navigation("StudentsSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
