name: Publish to develop environment

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

env:
  AZURE_WEBAPP_NAME: eduprime-dev-backend
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '7.0.x'

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Web API
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Install dependencies
        run: dotnet restore ./EduPrime.sln

      - name: Build .NET Web API
        run: dotnet build ./EduPrime.sln --configuration Release --no-restore
        
      - name: Set User Secrets
        run: |
          dotnet user-secrets set "ConnectionStrings:DefaultConnection" "Server=eduprimerserver.database.windows.net;Database=EduPrimeDevDB;User Id=L3ziU5GaSNTlVPO;Password=HkQ15jdGmMx9EmA" --project ./EduPrime.API
          dotnet user-secrets set "azureSettings:StorageAccountKey" "DefaultEndpointsProtocol=https;AccountName=eduprimestorage;AccountKey=DuTWfWavGYjWXXZ/FF6EiB02woEvnoyUB5XUsMsy5l+1Omwmj/mYICSIFP4JRtE19USQIg7+TKcc+AStS9kw5A==;EndpointSuffix=core.windows.net" --project ./EduPrime.API
          dotnet user-secrets set "azureSettings:EmployeesRfcsContainer" "employeesrfcs" --project ./EduPrime.API
          dotnet user-secrets set "azureSettings:EmployeesPicturesContainer" "employeespictures" --project ./EduPrime.API
          dotnet user-secrets set "azureSettings:StudentsPicturesContainer" "studentspictures" --project ./EduPrime.API
          dotnet user-secrets set "JwtSettings:Secret" "qYxJd6i6cqmvOBpoMrij2hBcGf7Gru" --project ./EduPrime.API
          dotnet user-secrets set "JwtSettings:Issuer" "https://localhost:44392/" --project ./EduPrime.API
          dotnet user-secrets set "JwtSettings:Audience" "https://localhost:44392/" --project ./EduPrime.API
          dotnet user-secrets set "JwtSettings:ValidTimeMinutes" "7" --project ./EduPrime.API
          dotnet user-secrets set "PasswordSettings:SaltSize" 16 --project ./EduPrime.API
          dotnet user-secrets set "PasswordSettings:KeySize" 32 --project ./EduPrime.API
          dotnet user-secrets set "PasswordSettings:Iterations" 10000 --project ./EduPrime.API

      - name: Publish .NET Web API
        run: dotnet publish ./EduPrime.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy .NET Web API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'


